---

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Initialize node - loadbalancer @ 192.168.100.140
      include: init-container.yml container_name=loadbalancer      lab_ip=192.168.100.140      

    - name: Initialize node - web1 @ 192.168.100.141
      include: init-container.yml container_name=web1              lab_ip=192.168.100.141

    - name: Initialize node - web2 @ 192.168.100.142
      include: init-container.yml container_name=web2              lab_ip=192.168.100.142

    - name: Initialize node - database @ 192.168.100.143
      include: init-container.yml container_name=database          lab_ip=192.168.100.143

    - name: Initialize node - metrics @ 192.168.100.144
      include: init-container.yml container_name=metrics           lab_ip=192.168.100.144

    - name: Patch hosts files
      become: yes
      include: patch-hosts.yml container_name=masterhost