---
# This playbook will install PostgreSQL and create db user and give permissions and enable pg_stat_statements extension.

- name: Install PostgreSQL package
  yum: name={{ item }} state=installed
  with_items:
   - postgresql-server
   - postgresql
   - postgresql-libs
  when: config_only == false

- name: Enable PostgreSQL service
  file:
    src: "/usr/lib/systemd/system/postgresql.service"
    dest: "/etc/systemd/system/multi-user.target.wants/postgresql.service"
    state: link

