---

- hosts: 127.0.0.1
  vars:
    main_ip: 192.168.100.180

---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

    - name: Create database
      influxdb_database:
        hostname: "{{main_ip}}"
        database_name: "{{influxdb_database_name}}"