---

  - name: Add influx repository
    copy:
      dest: /etc/yum.repos.d/influxdb.repo
      content: |
        [influxdb]
        name = InfluxDB Repository - RHEL \$releasever
        baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
        enabled = 1
        gpgcheck = 1
        gpgkey = https://repos.influxdata.com/influxdb.key 

  - name: Install Influxdb
    yum: name=influxdb state=present

  - name: Influxdb configuration
    copy:
      dest: /etc/influxdb/influxdb.conf
      src: influxdb.conf

  - name: Start Influxdb
    service: name=influxdb state=started enabled=yes