---
- name: Initialize static content root
  file:
    path: /srv/control-front
    state: directory
    owner: boss
  become: yes


- name: Copy static content
  copy:
    src: www
    dest: /srv/control-front

# disable IPv6 is messing things up 
#- name: Install nginx
#  package: name=nginx state=present
#  become: yes

- name: Copy nginx configuration for wordpress
  template: src=default.site dest=/etc/nginx/sites-enabled/default
  notify: restart nginx
  become: yes

- name: http service state
  service: name=nginx state=started enabled=yes
  become: yes