---
- name: Initialize static content root
  file:
    path: /srv/control-front
    state: directory
    owner: boss
  become: yes


- name: Copy static content
  copy:
    src: www
    dest: /srv/control-front

- name: Download gotty
  get_url:
    url: https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz
    dest: /tmp/gotty_linux_amd64.tar.gz

- name: Uncompress gotty
  unarchive:
    src: /tmp/gotty_linux_amd64.tar.gz
    dest: /srv/control-front

- name: Create gotty term trampoline
  copy:
    dest: /srv/control-front/start
    content: |
      bash $1

- name: Create gotty service entry
  copy:
    dest: /etc/systemd/system/gotty.service
    content: |
      [Unit]
      Description=GoTTY service
      After=network.target

      [Service]
      Type=simple
      User=boss
      ExecStart=/srv/control-front/gotty -w --permit-arguments bash /srv/control-front/start
      Restart=on-abort

      [Install]
      WantedBy=multi-user.target
  become: yes

- name: Daemon reload
  command: systemctl daemon-reload
  become: true

- name: Enable gotty service
  service: name=gotty state=started enabled=yes
  become: yes  

# disable IPv6 is messing things up 
#- name: Install nginx
#  package: name=nginx state=present
#  become: yes

- name: Configure nginx for static site
  template: src=default.site dest=/etc/nginx/sites-enabled/default
  notify: restart nginx
  become: yes

- name: http service state
  service: name=nginx state=started enabled=yes
  become: yes