- hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:

    - name: Enable "edge" repo
      lineinfile: dest=/etc/apk/repositories line="{{item.repo}}" state=present
      with_items:
        - repo: "http://dl-cdn.alpinelinux.org/alpine/edge/main"
        - repo: "http://dl-cdn.alpinelinux.org/alpine/edge/community"
        - repo: "http://dl-cdn.alpinelinux.org/alpine/edge/testing"      

    - name: Upgrade to the "edge"
      apk: 
        upgrade: yes