- hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars_files:
    - ../labconfig.yml

  tasks:
    - name: Setup network
      include: setup-network.yml

    - name: Setup LXD
      include: setup-lxd.yml    

  handlers:
    - name: restart network
      service:
        name: network
        status: restarted