---

    - name: Create SSH key (mkdir)
      file: 
        path: "{{lab.layout.confdir}}/ssh"  
        state: directory

    - name: Create SSH key      
      command: "ssh-keygen -q -t rsa -f {{lab.layout.confdir}}/ssh/id_rsa -C \"\" -N \"\""
      args:
        creates: "{{lab.layout.confdir}}/ssh/id_rsa"