---
- name: Install epel-release & yum-utils
  yum: name={{ item }} state=present    
  with_items: [epel-release, yum-utils]

- name: Install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  command: yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Enable PHP7.3
  command: yum-config-manager --enable remi-php73

- name: Install php-fpm and deps
  yum: name={{ item }} state=present    
  with_items: [php-cli, php-fpm php-mysql, php-json, php-opcache, php-mbstring, php-xml, php-gd, php-curl]

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm
