---
# -/- Playbook for ubuntu host -/-
# Playbook for Alpine host

#  - name: Add telegraf repo
#    become: true
#    copy:
#      dest: /etc/apt/sources.list.d/influxdata.list
#      content: |
#        deb https://repos.influxdata.com/debian stretch stable
#    when: config_only == false

#  - name: Add repository key
#    become: true
#    shell: curl -sL https://repos.influxdata.com/influxdb.key | apt-key add -    
#    when: config_only == false

#  - name: Install Telegraf
#    become: true
#    apt: name=telegraf update_cache=yes
#    when: config_only == false

  - name: Install Telegraf
    become: true
    package: name=telegraf state=installed
    when: config_only == false

#  - name: Add telegraf user to sudo
#    become: true
#    copy:
#      dest: /etc/sudoers.d/telegraf
#      src: sudoers.d/telegraf
#      mode: 0440
#    when: config_only == false

  - name: Configure telegraf
    become: true
    copy:
      dest: /etc/telegraf/telegraf.conf
      src: telegraf.conf

  - name: Deploy LXD monitoring script
    become: true
    copy:
      dest: /usr/local/sbin/telegraf-lxd-stats
      src: usr/local/sbin/telegraf-lxd-stats
      owner: telegraf
      mode: +x

  - name: Add telegraf config for LXD
    become: true
    copy:
      dest: /etc/telegraf/telegraf.d/
      src: telegraf.d/

  - name: Start Telegraf
    become: true
    service: name=telegraf state=restarted enabled=yes
