# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
#deleteDatasources:
#   - name: Graphite
#     orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
   # <string, required> name of the datasource. Required
 - name: influxdb-telegraf
   # <string, required> datasource type. Required
   type: influxdb
   # <string> url
   url: http://metrics:8086
   # <string> database name, if used
   database: telegraf
   # <bool> allow users to edit datasources from the UI.
   editable: true

