---

- name: Install MariaDB
  hosts: database
  connection: lxd 

  roles:
    - common
    - mariadb

- name: Install Wordpress
  hosts: web
  connection: lxd

  roles:
    - common
    - php-fpm
    - nginx
    - wordpress

- name: Install InfluxDB
  hosts: metrics
  connection: lxd

  roles:
    - common
    - influxdb
    - grafana

- name: Install telegraf
  hosts: masterhost
  
  roles:
    - telegraf

#- name: Install NginX
#  hosts: loadbalancer
#
#  roles:
#    - common
#    - nginx