---

- name: Install MariaDB
  hosts: database
  connection: lxd 

  roles:
    - common
    - telegraf-node
    - mariadb
    - wp-db-setup

- name: Install Wordpress
  hosts: web
  connection: lxd

  roles:
    - common
    - telegraf-node
    - php-fpm
    - nginx
    - wordpress
    - wordpress-plugins

- name: Install HAProxy
  hosts: loadbalancer

  roles:
    - common
    - telegraf-node
    - haproxy

- name: Install InfluxDB
  hosts: metrics
  connection: lxd

  roles:
    - common
    - influxdb
    - grafana

- name: Install telegraf
  hosts: masterhost
  
  roles:
    - telegraf-host
    - control-front
    - masterhost-setup

