---

- name: Configure CentOS
  hosts: containers
  connection: lxd

  roles:
    - common

- name: Install MariaDB
  hosts: database
  connection: lxd 

  roles:
    - mariadb

- name: Setup WP in database
  hosts: database
  connection: lxd

  roles:
    - wp-db-setup

- name: Install Wordpress
  hosts: web
  connection: lxd

  roles:
    - php-fpm
    - nginx
    - wordpress

- name: Install HAProxy
  hosts: loadbalancer

  roles:
    - haproxy

- name: Install InfluxDB
  hosts: metrics
  connection: lxd

  roles:
    - influxdb
    - grafana

- name: Install telegraf
  hosts: masterhost
  
  roles:
    - telegraf

