---
# This playbook deploys the whole application stack in this site.

- hosts: 127.0.0.1
  vars:
    main_ip: 192.168.100.180


- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: root

  roles:
    - db
