---

    - name: Node "{{remote_name}}" - add container to inventory
      add_host:
        name: "{{remote_name}}"
        hostname: "{{}remote_addr}"
        ansible_connection: ssh
        ansible_user: root
        ansible_ssh_pass: toor
      changed_when: false

    - name: Node "{{remote_name}}" - configure authorized_keys
      delegate_to: "{{remote_name}}"
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/boss/.ssh/id_rsa.pub') }}"

