---
# Playbook for ubuntu host

  - name: Add telegraf repo
    become: true
    copy:
      dest: /etc/apt/sources.list.d/influxdata.list
      content: |
        deb https://repos.influxdata.com/debian stretch stable

  - name: Add repository key
    become: true
    shell: curl -sL https://repos.influxdata.com/influxdb.key | apt-key add -    

  - name: Install Telegraf
    become: true
    apt: name=telegraf update_cache=yes

  - name: Configure telegraf
    become: true
    copy:
      dest: /etc/telegraf/telegraf.conf
      src: telegraf.conf

  - name: Deploy LXD monitoring script
    become: true
    copy:
      dest: /usr/local/sbin/lxd-telegraf-stats.py
      src: usr/local/sbin/lxd-telegraf-stats.py
      owner: telegraf
      mode: +x

  - name: Add telegraf config for LXD
    become: true
    copy:
      dest: /etc/telegraf/telegraf.d/lxd.conf
      src: telegraf.d/lxd.conf

  - name: Start Telegraf
    become: true
    service: name=telegraf state=restarted enabled=yes
