---

  - name: Add Grafana repository
    copy:
      dest: /etc/yum.repos.d/grafana.repo
      content: |
        [grafana]
        name=grafana
        baseurl=https://packages.grafana.com/oss/rpm
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.grafana.com/gpg.key

  - name: Install Grafana
    yum: name=grafana state=present

  - name: Configure Grafana
    copy:
      dest: /etc/grafana/grafana.ini
      src: grafana.ini

  - name: Provision Grafana (data sources & dashboards)
    copy:
      dest: /etc/grafana/provisioning/
      src: provisioning/

  - name: Start Grafana
    service: name=grafana-server state=restarted enabled=yes