---
lab:
  network:
    nodes:
      vm:
        description: VM host for containers
        ip: 192.168.100.146
      
      loadbalancer:
        ip: 192.168.100.140

      web1:
        ip: 192.168.100.141

      web2:
        ip: 192.168.100.142

      database:
        ip: 192.168.100.143

      metrics:
        ip: 192.168.100.144

      front:
        ip: 192.168.100.145

    hosts_file:
      - name: vm
      - name: loadbalancer
      - name: web1
      - name: web2
      - name: database
      - name: metrics
      - name: front
  
  layout:
    basedir: /opt/loadlab
    confdir: /opt/loadlab/config    
