---
lab:
  network:
    nodes:
      vm:
        description: VM host for containers
        ip: 192.168.100.146
      
      loadbalancer:
        description: HAProxy container
        ip: 192.168.100.140

      web1:
        description: Web node Nginx + PHP
        ip: 192.168.100.141

      web2:
        description: Web node Nginx + PHP
        ip: 192.168.100.142

      database:
        ip: 192.168.100.143

      metrics:
        description: Influx + Graphana
        ip: 192.168.100.144

      front:
        description: Lab pages and terminal
        ip: 192.168.100.145

    hosts_file:
      - "vm"
      - "loadbalancer"
      - "web1"
      - "web2"
      - "database"
      - "metrics"
      - "front"
  
  web:
    domain: loadlab.ragozin.info
    certificate: 

  path:
    basedir: /opt/loadlab
    confdir: /opt/loadlab/config
    sourcedir: /opt/loadlab/setup
