---
- name: Install nginx
  package: name=nginx state=present
  when: config_only == false

- name: Create dir for access.log
  file:
    path: /var/log/wordpress
    state: directory

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Configure telegraf pluding for nginx
  copy:
    src: telegraf.d
    dest: /etc/telegraf/
  notify: restart telegraf

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  when: enabled_firewalld and config_only == false

- name: http service state
  service: name=nginx state=started enabled=yes