---

- name: Debug on - define('WP_DEBUG', true );
  lineinfile:
    path: /srv/wordpress/wp-config.php
    regexp: '^define(.WP_DEBUG.,'
    line: define('WP_DEBUG', true );
  when: wp_debug_switch == "on"

- name: Debug on - define('WP_DEBUG', false );
  lineinfile:
    path: /srv/wordpress/wp-config.php
    regexp: '^define(.WP_DEBUG.,'
    line: define('WP_DEBUG', true );
  when: wp_debug_switch != "on"    

- name: Debug on - define( 'WP_DEBUG_LOG', true );
  lineinfile:
    path: /srv/wordpress/wp-config.php
    regexp: '^define(.WP_DEBUG_LOG.,'
    line: define( 'WP_DEBUG_LOG', true );
  when: wp_debug_switch == "on"

- name: Debug on - define( 'WP_DEBUG_LOG', false );
  lineinfile:
    path: /srv/wordpress/wp-config.php
    regexp: '^define(.WP_DEBUG_LOG.,'
    line: define( 'WP_DEBUG_LOG', false );
  when: wp_debug_switch != "on"


# TODO pg4wp debug

#- name: Debug on -
#  lineinfile:
#    src: "{{ lab.path.contentdir }}/wordpress/plugins/wppg/pg4wp/db.php"
#    path: /srv/wordpress/wp-content/db.php
#  when: wp_debug_switch == "on"
#
#- name: Deactivate Plugin WPPG - remove db.php
#  file:
#    path: /srv/wordpress/wp-content/db.php
#    state: absent
#  when: wp_debug_switch != "on"